import sys

import pytest

from tests.conftest import ROOT, SAMPLES
from tests.fakes import RX_PDF_LINES, router, text_pdf

UI = ROOT / "ui"


@pytest.fixture
def ui_env(client, fake_llm, monkeypatch):
    fake_llm.handler = router()
    from app.config import get_settings

    get_settings().summary_on_upload = False
    pid = client.post("/patients", json={"name": "Rahul Sharma", "sex": "male", "birth_year": 1979}).json()["_id"]
    client.post(f"/patients/{pid}/documents?sync=true", files={"file": ("lab.pdf", (SAMPLES / "lab_report_2024_03.pdf").read_bytes(), "application/pdf")})
    client.post(f"/patients/{pid}/documents?sync=true", files={"file": ("rx.pdf", text_pdf(RX_PDF_LINES), "application/pdf")})
    monkeypatch.syspath_prepend(str(UI))
    sys.modules.pop("api_client", None)
    sys.modules.pop("common", None)
    import api_client

    def _req(method, path, timeout=30.0, **kw):
        r = client.request(method, path, **kw)
        if r.status_code >= 400:
            raise api_client.ApiError(r.json().get("detail", "error"))
        return r.json() if "json" in r.headers.get("content-type", "") else r.content

    monkeypatch.setattr(api_client, "_req", _req)
    yield pid
    sys.modules.pop("api_client", None)
    sys.modules.pop("common", None)


def _open(pid, page):
    from streamlit.testing.v1 import AppTest

    at = AppTest.from_file(str(UI / "app.py"), default_timeout=60)
    at.session_state["patient_id"] = pid
    at.switch_page(f"views/{page}.py")
    at.run()
    return at


@pytest.mark.parametrize("page", ["perry", "upload", "timeline", "document", "trends", "confirm", "medications", "fhir"])
def test_page_renders(ui_env, page):
    at = _open(ui_env, page)
    assert not at.exception, [e.message for e in at.exception]
    text = " ".join(m.value for m in at.markdown)
    assert "Rahul Sharma" in text


def test_document_source_picker_and_summary(ui_env):
    at = _open(ui_env, "document")
    docs = [s for s in at.selectbox if s.label == "Choose a document"][0]
    lab_opt = next(o for o in docs.options if "Lab report" in o)
    docs.select(lab_opt).run()
    src = [s for s in at.selectbox if s.label == "Show where a value came from"][0]
    src.select(next(o for o in src.options if o.startswith("HbA1c"))).run()
    assert not at.exception
    assert any("Source of:" in m.value for m in at.markdown)
    joined = " ".join(m.value for m in at.markdown)
    assert "This summary was generated by software" in joined
    assert "HbA1c" in joined


def test_timeline_shows_reconciliation_and_cards(ui_env):
    at = _open(ui_env, "timeline")
    joined = " ".join(m.value for m in at.markdown)
    assert "Current medicines" in joined and "Prescription" in joined and "Lab report" in joined


def test_perry_page_chats_and_has_voice_controls(ui_env):
    from app.config import get_settings

    get_settings().perry_mode = "template"
    at = _open(ui_env, "perry")
    assert not at.exception, [e.message for e in at.exception]
    joined = " ".join(m.value for m in at.markdown)
    assert "Hey there!" in joined and 'class="pv pv-live"' in joined and "Ready when you are!" in joined
    labels = [b.label for b in at.button]
    for label in ("Latest Report", "My Medicines", "My Timeline", "Recent Documents", "Pending Confirmations", "Compare Reports"):
        assert label in labels
    assert [r.label for r in at.radio] == ["Speech recognition"]
    assert any(t.label == "Read answers to voice questions aloud" and t.value is True for t in at.toggle)
    assert any(s.label == "Reply language" for s in at.selectbox)
    next(b for b in at.button if b.label == "My Medicines").click().run()
    at.run()
    assert not at.exception, [e.message for e in at.exception]
    joined = " ".join(m.value for m in at.markdown)
    assert "Tab Glycomet 500" in joined
    assert at.session_state["perry_state"] == "explaining"
    assert 'data-state="explaining"' in joined
    assert any(b.label == "🔊" for b in at.button)
    at.radio[0].set_value("browser").run()
    assert not at.exception, [e.message for e in at.exception]
    assert "Language you will speak" in [s.label for s in at.selectbox]


def test_overview_medications_and_fhir_pages(ui_env):
    at = _open(ui_env, "trends")
    assert any("Current medicines" in m.value for m in at.markdown)
    at = _open(ui_env, "medications")
    assert any("Glycomet" in m.value for m in at.markdown)
    at = _open(ui_env, "fhir")
    assert not at.exception, [e.message for e in at.exception]
    assert any("Bundle" in m.value or "Patient" in m.value for m in at.markdown)
