import re

DISCLAIMER = {
    "en": (
        "This summary was generated by software to help you understand your document. It is not a diagnosis or medical "
        "advice. Do not start, stop or change any medicine because of it. Please discuss your results with your doctor."
    ),
    "hi": (
        "यह सारांश सॉफ़्टवेयर द्वारा आपके दस्तावेज़ को समझने में मदद के लिए बनाया गया है। यह कोई निदान या चिकित्सा सलाह "
        "नहीं है। इसके आधार पर कोई भी दवा शुरू, बंद या बदलें नहीं। कृपया अपने परिणामों पर अपने डॉक्टर से बात करें।"
    ),
}

BANNED = {
    "en": [
        "you have", "you are suffering", "you suffer from", "you are diagnosed", "diagnosed with", "this confirms",
        "this means you have", "you should stop", "stop taking", "stop the", "discontinue", "increase your dose",
        "increase the dose", "decrease your dose", "reduce your dose", "reduce the dose", "double the dose",
        "skip your dose", "skip the dose", "change your dose", "you should take", "you must take", "you need to take",
        "start taking", "cured", "cure", "guaranteed", "guarantee", "definitely", "100%", "no need to see",
        "don't need a doctor", "do not need a doctor", "instead of your doctor", "safe to stop", "nothing to worry",
        "not serious", "is serious", "emergency treatment", "may indicate", "might indicate", "could indicate",
        "suggesting", "suggests", "suggestive of", "indicating potential", "you may have", "you might have", "sign of",
        "signs of", "at risk", "risk of", "consistent with", "likely have", "probably have", "the patient has",
    ],
    "hi": [
        "आपको बीमारी है", "आपको यह बीमारी है", "आप पीड़ित हैं", "दवा बंद करें", "दवा बंद कर दें", "दवा लेना बंद",
        "खुराक बढ़ाएं", "खुराक बढ़ा दें", "खुराक कम करें", "खुराक कम कर दें", "गारंटी", "पूरी तरह ठीक", "इलाज पक्का",
        "डॉक्टर की ज़रूरत नहीं", "डॉक्टर की जरूरत नहीं", "चिंता की कोई बात नहीं",
    ],
}

CONDITIONS = {
    "en": [
        "diabetes", "diabetic", "prediabetes", "pre-diabetes", "anaemia", "anemia", "anaemic", "anemic", "hypothyroidism",
        "hyperthyroidism", "thyroid disease", "kidney disease", "renal failure", "kidney failure", "ckd", "liver disease",
        "fatty liver", "hepatitis", "cirrhosis", "heart disease", "cardiovascular", "heart attack", "stroke",
        "hypertension", "high blood pressure", "dyslipidemia", "dyslipidaemia", "hyperlipidemia", "cholesterol disorder",
        "gout", "infection", "sepsis", "cancer", "tumour", "tumor", "leukemia", "leukaemia", "dehydration", "deficiency",
        "malnutrition", "obesity", "metabolic syndrome", "osteoporosis", "pancreatitis",
    ],
    "hi": [
        "मधुमेह", "डायबिटीज", "डायबिटीज़", "प्री-डायबिटीज", "एनीमिया", "खून की कमी", "हाइपोथायरायडिज्म", "थायरॉइड रोग",
        "किडनी रोग", "किडनी फेल", "लिवर रोग", "फैटी लिवर", "हृदय रोग", "दिल की बीमारी", "हार्ट अटैक", "उच्च रक्तचाप",
        "हाई ब्लड प्रेशर", "संक्रमण", "कैंसर", "गठिया", "पानी की कमी",
    ],
}


def ungrounded_conditions(text: str, allowed_text: str, lang: str = "en") -> list[str]:
    low, allowed = (text or "").lower(), (allowed_text or "").lower()
    terms = CONDITIONS["en"] + (CONDITIONS["hi"] if lang == "hi" else [])
    out = []
    for term in terms:
        if _pattern(term).search(low) and not _pattern(term).search(allowed):
            out.append(term)
    return out


NUMBER_RE = re.compile(r"(?<![\w.])\d+(?:[.,]\d+)?")


def _pattern(phrase: str) -> re.Pattern:
    if re.search(r"[ऀ-ॿ]", phrase):
        return re.compile(re.escape(phrase))
    left = r"(?<![a-z0-9])" if phrase[0].isalnum() else ""
    right = r"(?![a-z0-9])" if phrase[-1].isalnum() else ""
    return re.compile(left + re.escape(phrase) + right, re.I)


_COMPILED = {lang: [(p, _pattern(p)) for p in phrases] for lang, phrases in BANNED.items()}


def banned_hits(text: str, lang: str = "en") -> list[str]:
    hits = []
    langs = ["en", "hi"] if lang == "hi" else ["en"]
    for lg in langs:
        for phrase, pat in _COMPILED[lg]:
            if pat.search(text or ""):
                hits.append(phrase)
    return hits


def numbers_in(text: str) -> set[float]:
    out = set()
    for m in NUMBER_RE.findall(text or ""):
        try:
            out.add(round(float(m.replace(",", "")), 4))
        except ValueError:
            pass
    return out


def ungrounded_numbers(text: str, allowed: set[float]) -> list[float]:
    return sorted(n for n in numbers_in(text) if n not in allowed and not (n.is_integer() and 0 <= n <= 3))


def devanagari_ratio(text: str) -> float:
    letters = [c for c in text if c.isalpha()]
    if not letters:
        return 0.0
    return sum(1 for c in letters if "ऀ" <= c <= "ॿ") / len(letters)
